theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs
color_scheme: light
title: Kalavar
description: A powerful database system, written using pure Rust
logo: "/assets/images/word_banner_transparent.png"
image: "/assets/images/word_banner_transparent.png"

permalink: pretty
search_enabled: true
search:
  heading_level: 4
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

heading_anchors: true

aux_links:
  "View Repository":
    - "//github.com/KalavarDB/core"
  "<!-- <img width=\"45px\" height=\"45px\" src=\"https://discord.com/assets/f8389ca1a741a115313bede9ac02e2c0.svg\"/> --> Join the Discord":
    - "//discord.gg/jUGS8UsgUF"

aux_links_new_tab: true

nav_sort: case_sensitive

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2020 Thomas Bardsley. Distributed under the <a href=\"https://github.com/fatalcenturion/kalavar-core/tree/master/LICENSE.txt\">Mozilla Public License V2.0</a><br>By using this site you agree to our <a href=\"/privacy/\">privacy policy</a>"

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false


ga_tracking: G-BCP5QK4JZY
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)